import com.replaymod.gradle.preprocess.Node
import groovy.json.JsonSlurper

plugins {
    alias(libs.plugins.preprocessor)
    alias(libs.plugins.git.version)

    alias(libs.plugins.fabric.loom.noremap).apply(false)
    alias(libs.plugins.fabric.loom.remap).apply(false)
    alias(libs.plugins.yamlang).apply(false)
    alias(libs.plugins.replace.token).apply(false)
}

ext.isNonObfuscatedMc = { String mcVersion -> !mcVersion.startsWith("1.") }

preprocess {
    strictExtraMappings = false

    List<Node> nodes = new JsonSlurper().parseText(file("versions.json").text)
            .collect { String version, Map meta -> createNode(version, meta.code, meta.mappings) }
    nodes.eachWithIndex { node, index ->
        if (index > 0) {
            nodes[index - 1].link(node, null)
        }
    }
}

def details = null
try {
    details = versionDetails()
} catch (Exception ignored) {
}

def branch = details?.branchName?.replace("/", "-")
version = [
        project.mod_version,
        branch in ["main", "master"] ? null : branch,
        details?.gitHash,
        details != null ? "dirty" : null,
].findAll { it }.join("-")

tasks.register("cleanPreprocessSources") {
    List<File> preprocessedDirs = subprojects.collect { it.layout.buildDirectory.dir("preprocessed").get().asFile }

    doFirst {
        preprocessedDirs.forEach { it.deleteDir() }
    }
}
