import groovy.json.JsonSlurper

pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "Jitpack"
            url = "https://jitpack.io"
        }
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.replaymod.preprocess") {
                useModule("com.github.Fallen-Breath:preprocessor:${requested.version}")
            }
        }
    }
}

def versions = new JsonSlurper().parseText(file("versions.json").text)

versions.each { String mcVersion, Map meta ->
    include(":$mcVersion")
    ProjectDescriptor proj = project(":$mcVersion")
    File location = file("versions/$mcVersion")
    location.mkdirs()
    proj.setProjectDir(location)
    proj.setBuildFileName("../../common.gradle")
}

gradle.beforeProject { Project p ->
    def meta = versions[p.name]
    if (meta != null) {
        p.ext.minecraft_version = p.name
        p.ext.minecraft_dependency = meta.dep
        p.ext.minecraft_out = meta.out
        p.ext.java_version = meta.java
        p.ext.fabric_version = meta.fabric
        p.ext.libgui_version = meta.libgui
        p.ext.modmenu_version = meta.modmenu
    }
}

include(":fabricWrapper")
