import groovy.json.JsonBuilder
import groovy.json.JsonSlurper

plugins {
    id("java-library")
}

base {
    version = project.parent.version
    group = project.maven_group
    archivesName = "${project.archives_base_name}-all"
}

Set<Project> fabricSubprojects = project.rootProject.subprojects.findAll { it.name != "fabricWrapper" }

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

Closure<List<Task>> submodJarTasks = {
    fabricSubprojects.collect { subproject ->
        String taskName = subproject.tasks.names.contains("remapJar") ? "remapJar" : "jar"
        subproject.tasks.named(taskName).get()
    }
}

jar {
    // Disable cache
    outputs.upToDateWhen { false }
    dependsOn { submodJarTasks() }

    from(project.rootProject.file("LICENSE"))
    from(layout.buildDirectory.dir("tmp/submods"))

    doFirst {
        delete fileTree(layout.buildDirectory.dir("tmp/submods/META-INF/jars"))
        copy {
            from { submodJarTasks()*.outputs.files }
            into(layout.buildDirectory.dir("tmp/submods/META-INF/jars"))
        }
    }
}

processResources {
    // Disable cache
    outputs.upToDateWhen { false }

    inputs.property("mod_version", project.version)
    inputs.property("mod_id", project.mod_id)
    inputs.property("mod_name", project.mod_name)
    inputs.property("mod_sources", project.mod_sources)
    inputs.property("mod_license", project.mod_license)

    inputs.property("archives_base_name", project.archives_base_name)

    filesMatching("fabric.mod.json") {
        expand(["mod_version": inputs.properties["mod_version"],
                "mod_id"     : inputs.properties["mod_id"],
                "mod_name"   : inputs.properties["mod_name"],
                "mod_sources": inputs.properties["mod_sources"],
                "mod_license": inputs.properties["mod_license"],
        ])
    }

    def outputJson = layout.buildDirectory.file("resources/main/fabric.mod.json").get().asFile
    def archivesBaseName = project.archives_base_name

    doLast {
        def json = new JsonSlurper().parse(outputJson)
        json.depends.minecraft = fabricSubprojects.collect { it.minecraft_dependency }
        json.jars = fabricSubprojects.collect { subproject ->
            [file: "META-INF/jars/${archivesBaseName}-mc${subproject.minecraft_out}-${subproject.version}.jar"]
        }
        outputJson.text = new JsonBuilder(json).toPrettyString()
    }
}