[versions]
# Gradle Plugins
fabric-loom = "1.18.4"
preprocessor = "26.1-hack-SNAPSHOT"
git-version = "5.1.0"
yamlang = "1.5.0"
replace-token = "1.2.0"

# modApi
fabric-loader = "0.19.5"
lombok = "1.18.48"

[plugins]
fabric-loom-noremap = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
fabric-loom-remap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
preprocessor = { id = "com.replaymod.preprocess", version.ref = "preprocessor" }
git-version = { id = "com.palantir.git-version", version.ref = "git-version" }
yamlang = { id = "me.fallenbreath.yamlang", version.ref = "yamlang" }
replace-token = { id = "top.hendrixshen.replace-token", version.ref = "replace-token" }

[libraries]
# modApi
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
